FROM cassandra:latest

WORKDIR /initdb

COPY init.cql /initdb/init.cql

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["cassandra", "-f"]
